baseURL = 'http://localhost:1313/'
languageCode = 'zh-cn'
title = 'Knowledge Plus'
theme = "loveit"
enableEmoji = true
enableInlineShortcodes = true
hasCJKLanguage = true
timeZone = "Asia/Shanghai"
uglyURLs = true

[menu]
    [[menu.main]]
        identifier = "posts"
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = ""
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
        post = ""
        name = "所有文章"
        url = "/posts/"
        # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
        title = ""
        weight = 1
    [[menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "标签"
        url = "/tags/"
        title = ""
        weight = 2
    [[menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "分类"
        url = "/categories/"
        title = ""
        weight = 3

[frontmatter]
date = ['date', 'publishDate', 'lastmod']
expiryDate = ['expiryDate']
lastmod = [':git', 'lastmod', 'date', 'publishDate']
publishDate = ['publishDate', 'date']

[params]
_merge = "depp"
version = "0.2.X"
description = "知识+"
# 网站关键词
keywords = ["Knowledge Plus", "Knowledge", "知识+"]
#  哪种哈希函数用来 SRI, 为空时表示不使用 SRI
# ("sha256", "sha384", "sha512", "md5")
fingerprint = "sha256"
#  日期格式
dateFormat = "2006-01-02"
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = []

#  应用图标配置
[params.app]
# 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
title = "Knowledge Plus"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
svgFavicon = ""
# Android 浏览器主题色
themeColor = "#ffffff"
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10磁贴颜色
tileColor = "#da532c"

#  搜索配置
[params.search]
enable = true
# 搜索引擎的类型 ("lunr", "algolia")
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = "请输入关键词"
#  最大结果数目
maxResultLength = 10
#  结果内容片段长度
snippetLength = 50
#  搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
#  是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false

# 页面头部导航栏配置
[params.header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "fixed"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"
#  页面头部导航栏标题配置
[params.header.title]
# LOGO 的 URL
logo = ""
# 标题名称
name = "Knowledge Plus"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
#  是否为标题显示打字机动画
typeit = false

# 页面底部信息配置
[params.footer]
enable = true
#  自定义内容 (支持 HTML 格式)
custom = ''
#  是否显示 Hugo 和主题信息
hugo = false
#  是否显示版权信息
copyright = true
#  是否显示作者
author = true
# 网站创立年份
since = 2021
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = ""
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

#  Section (所有文章) 页面配置
[params.section]
# section 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

#  List (目录或标签) 页面配置
[params.list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

# 主页配置
[params.home]
#  RSS 文章数目
rss = 10
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
avatarURL = ""
#  主页显示的网站标题 (支持 HTML 格式)
title = "Knowledge Plus"
# 主页显示的网站副标题
subtitle = "知识+"
# 是否为副标题显示打字机动画
typeit = false
# 是否显示社交账号
social = true
#  免责声明 (支持 HTML 格式)
disclaimer = ""
# 主页文章列表
[params.home.posts]
enable = true
# 主页每页显示文章数量
paginate = 6
#  被 params.page 中的 hiddenFromHomePage 替代
# 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
defaultHiddenFromHomePage = false

# 作者的社交信息设置
[params.social]
GitHub = "sqmt"
Email = "rafit@qq.com"
RSS = true #

#  文章页面配置
[params.page]
#  是否在主页隐藏一篇文章
hiddenFromHomePage = false
#  是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
#  是否使用 twemoji
twemoji = true
# 是否使用 lightgallery
lightgallery = true
#  是否使用 ruby 扩展语法
ruby = true
#  是否使用 fraction 扩展语法
fraction = true
#  是否使用 fontawesome 扩展语法
fontawesome = true
# 是否在文章页面显示原始 Markdown 文档链接
linkToMarkdown = true
#  是否在 RSS 中显示全文内容
rssFullText = false
#  目录配置
[params.page.toc]
# 是否使用目录
enable = true
#  是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = false
#  代码配置
[params.page.code]
# 是否显示代码块的复制按钮
copy = true
#  Mapbox GL JS 配置
[params.page.mapbox]
# Mapbox GL JS 的 access token
accessToken = ""
# 浅色主题的地图样式
lightStyle = "mapbox://styles/mapbox/light-v9"
# 深色主题的地图样式
darkStyle = "mapbox://styles/mapbox/dark-v9"
# 是否添加 NavigationControl
navigation = true
# 是否添加 GeolocateControl
geolocate = true
# 是否添加 ScaleControl
scale = true
# 是否添加 FullscreenControl
fullscreen = true
#  文章页面的分享信息设置
[params.page.share]
enable = true
Weibo = true
Baidu = true
Evernote = true
#  评论系统设置
[params.page.comment]
enable = false

#  网站 SEO 配置
[params.seo]
# 图片 URL
image = ""
# 缩略图 URL
thumbnailUrl = ""

#  Cookie 许可配置
[params.cookieconsent]
enable = false

# 作者配置
[author]
name = "sqmt"
email = "rafit@qq.com"
link = ""

# Permalinks 配置
[Permalinks]
    posts = ":year/:month/:filename"